### PR TITLE
change the version of panda

### PR DESCRIPTION
**Pull request by SamirPS**
Change the version of panda in requirements #31

### CODE REVIEW

**Comment by SamirPS** [comment]
@Dubrzr

**Comment by Dubrzr** [comment]
Hello @SamirPS : can you maybe change it to "pandas>=0.23.0" instead ? Have you tried it with another pandas version? Which one? Thanks!

**Comment by SamirPS** [comment]
@Dubrzr i didn't have the time to check with other pandas version

**Review by Dubrzr — APPROVED** [review]

**Comment by Dubrzr** [comment]
Thank you @SamirPS !

**Pull request merged**
